ALTER TABLE allergies
	RENAME COLUMN START TO START_DATE;
ALTER TABLE allergies
	RENAME COLUMN STOP TO START_DATE;
	
ALTER TABLE allergies
	ALTER COLUMN STOP_DATE TYPE DATE USING STOP_DATE::DATE,
	ALTER COLUMN START_TIME TYPE DATE USING START_TIME::DATE;

SELECT * FROM allergies;

SELECT * FROM PATIENTS;

ALTER TABLE


